// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzmmrvnmudvipltbjedo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bW1ydm5tdWR2aXBsdGJqZWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTI0OTQsImV4cCI6MjA3NDYyODQ5NH0.EVH3I5MwgnaXQfrh5LJymhd-TefC5FoH-1edR7a2gis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});